import type { Track, Video, Film, WebLink } from "./media-context"

export const sampleTracks: Track[] = [
  {
    id: "1",
    title: "Midnight Dreams",
    artist: "Aurora Waves",
    album: "Nocturnal",
    duration: 234,
    coverUrl: "https://images.unsplash.com/photo-1614149162883-504ce4d13909?w=300&h=300&fit=crop",
  },
  {
    id: "2",
    title: "Electric Pulse",
    artist: "Neon Lights",
    album: "Voltage",
    duration: 198,
    coverUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop",
  },
  {
    id: "3",
    title: "Ocean Breeze",
    artist: "Coastal Vibes",
    album: "Serenity",
    duration: 312,
    coverUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=300&h=300&fit=crop",
  },
  {
    id: "4",
    title: "Urban Rhythm",
    artist: "City Beats",
    album: "Metropolis",
    duration: 267,
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop",
  },
  {
    id: "5",
    title: "Stellar Journey",
    artist: "Cosmic Sound",
    album: "Galaxy",
    duration: 289,
    coverUrl: "https://images.unsplash.com/photo-1446185250204-f94591f7d702?w=300&h=300&fit=crop",
  },
  {
    id: "6",
    title: "Summer Nights",
    artist: "Tropical Beat",
    album: "Paradise",
    duration: 245,
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&h=300&fit=crop",
  },
]

export const sampleVideos: Video[] = [
  {
    id: "1",
    title: "Mountain Adventures",
    description: "Exploring the majestic peaks and valleys",
    duration: 420,
    thumbnailUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=640&h=360&fit=crop",
  },
  {
    id: "2",
    title: "City at Night",
    description: "The urban landscape comes alive after dark",
    duration: 380,
    thumbnailUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=640&h=360&fit=crop",
  },
  {
    id: "3",
    title: "Ocean Documentary",
    description: "Diving deep into marine life",
    duration: 560,
    thumbnailUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=640&h=360&fit=crop",
  },
  {
    id: "4",
    title: "Tech Showcase",
    description: "Latest innovations in technology",
    duration: 290,
    thumbnailUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=640&h=360&fit=crop",
  },
]

export const sampleFilms: Film[] = [
  {
    id: "1",
    title: "Neon Horizon",
    year: 2024,
    genre: ["Sci-Fi", "Action"],
    rating: 8.5,
    posterUrl: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=300&h=450&fit=crop",
    description: "In a dystopian future, a group of rebels fight against a corrupt AI overlord.",
    director: "James Chen",
  },
  {
    id: "2",
    title: "The Last Garden",
    year: 2023,
    genre: ["Drama", "Romance"],
    rating: 7.8,
    posterUrl: "https://images.unsplash.com/photo-1518882605630-8996a190f7ae?w=300&h=450&fit=crop",
    description: "A heartfelt story of love and loss set in a beautiful botanical garden.",
    director: "Sofia Rodriguez",
  },
  {
    id: "3",
    title: "Shadow Protocol",
    year: 2024,
    genre: ["Thriller", "Mystery"],
    rating: 8.2,
    posterUrl: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=300&h=450&fit=crop",
    description: "A spy uncovers a conspiracy that threatens global security.",
    director: "Michael Torres",
  },
  {
    id: "4",
    title: "Cosmic Dreams",
    year: 2023,
    genre: ["Sci-Fi", "Adventure"],
    rating: 8.9,
    posterUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=300&h=450&fit=crop",
    description: "Astronauts embark on humanity\'s first interstellar journey.",
    director: "Elena Park",
  },
  {
    id: "5",
    title: "Urban Tales",
    year: 2024,
    genre: ["Drama", "Comedy"],
    rating: 7.5,
    posterUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=300&h=450&fit=crop",
    description: "Interconnected stories of everyday people in a bustling city.",
    director: "David Kim",
  },
  {
    id: "6",
    title: "The Deep",
    year: 2023,
    genre: ["Horror", "Thriller"],
    rating: 7.9,
    posterUrl: "https://images.unsplash.com/photo-1551244072-5d12893278ab?w=300&h=450&fit=crop",
    description: "A deep-sea research team encounters something ancient and terrifying.",
    director: "Rachel Green",
  },
  {
    id: "7",
    title: "Golden Hour",
    year: 2024,
    genre: ["Romance", "Drama"],
    rating: 8.1,
    posterUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=450&fit=crop",
    description: "Two strangers meet during a magical sunset and their lives intertwine.",
    director: "Anna White",
  },
  {
    id: "8",
    title: "Circuit Breaker",
    year: 2023,
    genre: ["Action", "Sci-Fi"],
    rating: 8.4,
    posterUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=300&h=450&fit=crop",
    description: "A hacker discovers a way to control reality through code.",
    director: "Marcus Lee",
  },
]

export const sampleLinks: WebLink[] = [
  {
    id: "1",
    title: "GitHub",
    url: "https://github.com",
    category: "Development",
    favicon: "https://github.githubassets.com/favicons/favicon.svg",
    description: "Where the world builds software",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Vercel",
    url: "https://vercel.com",
    category: "Development",
    favicon: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico",
    description: "Develop, Preview, Ship",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    title: "Dribbble",
    url: "https://dribbble.com",
    category: "Design",
    favicon: "https://cdn.dribbble.com/assets/favicon-b38525134603b9513174ec887944bde1a869eb6cd414f4d640ee48ab2a15a26b.ico",
    description: "Discover the world\'s top designers",
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "4",
    title: "Spotify",
    url: "https://spotify.com",
    category: "Entertainment",
    description: "Music for everyone",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "5",
    title: "Netflix",
    url: "https://netflix.com",
    category: "Entertainment",
    description: "Watch TV shows and movies",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "6",
    title: "MDN Web Docs",
    url: "https://developer.mozilla.org",
    category: "Development",
    description: "Resources for developers, by developers",
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "7",
    title: "Figma",
    url: "https://figma.com",
    category: "Design",
    description: "Collaborative design tool",
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "8",
    title: "YouTube",
    url: "https://youtube.com",
    category: "Entertainment",
    description: "Video sharing platform",
    createdAt: new Date("2024-03-15"),
  },
]

export const linkCategories = ["All", "Development", "Design", "Entertainment", "News", "Social"]
export const filmGenres = ["All", "Sci-Fi", "Action", "Drama", "Romance", "Thriller", "Mystery", "Horror", "Comedy", "Adventure"]
